// <auto-generated />
using CoffeeDelivery.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeDelivery.Migrations.RequestItemDb
{
    [DbContext(typeof(RequestItemDbContext))]
    [Migration("20230418215040_Addnewcamps")]
    partial class Addnewcamps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CoffeeDelivery.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Prices")
                        .HasColumnType("int");

                    b.Property<int>("Products")
                        .HasColumnType("int");

                    b.Property<int>("QtdAddedToCart")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RequestItems");
                });
#pragma warning restore 612, 618
        }
    }
}
